version: "3"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "film"
      # So you don't have to use root, but you can if you like
      # You can use whatever password you like
      MYSQL_ROOT_PASSWORD: "qwer1234%"
      # Password for root access
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" 
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    volumes:
      - /Users/jin/Documents/dev/github_repo/docker-mysql/knou:/var/lib/mysql
